name: MY-INPUT

on:
  workflow_dispatch:
    inputs:
      SERVICE_NAME:
        choice:
        type: choice
        options:
          - L Service
          - S Service
        required: true
      OTHER_INPUT:
        description: 'select'
        type: choice
        options:
          - O Service
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  l-Service:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.SERVICE_NAME   == 'L Service'}}
    steps:
      - name: "l-service"
        run: "echo l-service"

  S-Service:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.SERVICE_NAME   == 'S Service'}}
    steps:
      - name: "s-service"
        run: "echo s-service"

  O-Service:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.OTHER_INPUT   == 'O Service'}}
    steps:
      - name: "o-service"
        run: "echo o-service"
